
import React from 'react'
import { Stack } from '@mui/material'
import { IconButton } from "@mui/material"
import { deepOrange } from '@mui/material/colors';
import ColorLensIcon from '@mui/icons-material/ColorLens';
import MultilineChartIcon from '@mui/icons-material/MultilineChart';
import RemoveCircleOutlineIcon from '@mui/icons-material/RemoveCircleOutline';

/**
 * Generates the buttons for controlling tracktype, color, and deleting tracks. Use "TrackListener" 
 * component to listen for the events generated by these buttons.
 */

function TrackControls(props) {

    const color = props.isDark ? deepOrange[500] : deepOrange[100]
    const highlight = props.isDark ? deepOrange[200] : deepOrange[500]

    return (
        <Stack marginTop={-props.gap+ "px"} marginBottom={ "0px"} alignItems={"flex-end"} style={{float: "right"}}>
                <IconButton className='trackButtons' id={"toggleTrackType_" + props.id} sx={{
                    backgroundColor: color,
                    borderRadius: 1,
                    // height: buttonHeight,
                    '&:hover': {
                        backgroundColor: highlight
                    }
                }}
                >
                    <MultilineChartIcon fontSize="small" className="handle_image" />
                </IconButton>

                <IconButton className='trackButtons'id={"deleteTrack_" + props.id} sx={{
                    backgroundColor: color,
                    borderRadius: 1,
                    // height: buttonHeight,
                    '&:hover': {
                        backgroundColor: highlight
                    }
                }}
                >
                    <RemoveCircleOutlineIcon fontSize="small" className="handle_image" />
                </IconButton>
                <IconButton className='trackButtons' id={"pickColor_" + props.id} sx={{
                    backgroundColor: color,
                    borderRadius: 1,
                    // height: buttonHeight,
                    '&:hover': {
                        backgroundColor: highlight
                    }
                }}>
                    <ColorLensIcon fontSize="small" className="handle_image" />
                </IconButton>

        </Stack>
    )
}

export default TrackControls